upstream vendas_service {
    server vendas:8000;
}

upstream financeiro_service {
    server financeiro:8001;
}

server {
    listen 80;
    server_name localhost;

    location /vendas/ {
        proxy_pass http://vendas_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /financeiro/ {
        proxy_pass http://financeiro_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        return 200 '{"status":"ok","service":"nginx"}';
        add_header Content-Type application/json;
    }
}
